//
// SCRIPT FOR CREATING HSQL DATABASE SQL CODE
//
def INT_TYPES = [SMALLINT:1, TINYINT:1, INTEGER:1, BIGINT:1]
def sql = '';
def tables = db.listTables();
for(table in tables) {
  def cols = table.listColumns()
  def colCount = cols.length
  def i = 0
  if(dropTablePolicy == 'dropTablesIfExists')
    sql += 'DROP TABLE IF EXISTS ' + table.name + ';\n'
  
  sql += 'CREATE'
  if(dropTablePolicy == 'createIfNotExists')
    sql += ' IF NOT EXISTS'
  sql += ' TABLE ' + table.name + ' (\n'
  for(col in cols) {
    sql += '\t' + col.name + ' ' + col.type;
    def type = col.type.toUpperCase()
    if(type == 'FLOAT' || type == 'DOUBLE' || type == 'NUMERIC' || type == 'DECIMAL') {
      sql += ' (' + typeSize
      if(col.floatDecimals > 0)
        sql += ', ' + col.floatDecimals;
      sql += ')'
    }
    else if(INT_TYPES.get(col.type) == null) {
      sql += ' (' + col.typeSize + ')'
    }
    
    if(col.defaultValue)
      sql += ' DEFAULT ' + col.defaultValue
    if(col.autoInc)
      sql += ' GENERATED BY DEFAULT AS IDENTITY'
    if(col.allowsNull() == false)
      sql += ' NOT NULL'
    if(col.pk)
      sql += ' PRIMARY KEY'
    if(i < colCount - 1)
      sql += ','
    sql += '\n'
    i++
  }
}

// NOW CREATE FOREIGN KEYS
for(table in tables) {
  // ONE MORE LOOP FOR CONSTRAINTS
  def cols = table.listColumns()
  def i = 0
  for(col in cols) {
    if(col.fk) {
      sql += ',\nCONSTRAINT fk_' + table.name + '_' + col.name + ' FOREIGN KEY (' + col.name + ')'
      sql += ' REFERENCES ' + col.refTable
      if(col.refColumn)
        sql += ' (' + col.refColumn + ')'
      if(col.)
    }
  }
  sql += ');\n'
}

return sql

/*#foreach($col in $columns)
#if($col.isFk())
CONSTRAINT fk_${table.name}_$col.name FOREIGN KEY $col.name
           REFERENCES $col.refTable.name #if($col.refColumn) ($col.refColumn.name) #end
##             #if($col.) ON DELETE
##        [index_name] (index_col_name,...) [reference_definition]
##        REFERENCES tbl_name [(index_col_name,...)]
##               [MATCH FULL | MATCH PARTIAL]
##               [ON DELETE reference_option]
##               [ON UPDATE reference_option]
#end ## $col.isFk()
#end
*/
